### ISSUE TITLE
Average Damage Per Round Calculator [Feature Request]

### ISSUE THREAD

**Issue by jasonmherber** [Freymaurer/PathfinderAttackSimulator#14]
I will suggest that you consider instead of having the application roll dice, that it uses the likelihood of hitting as a multiplier to the average damage. So:

At level 12, my attack routine is +17/+12 for 1d10+10 damage. If my target AC is 27 (the statistical average pulled from the bestiary entries for CR 12 encounters):

I need a 10 to hit with my full BAB attack, which means I have a 55% chance of hitting, or a .55 multiplier to damage. My average damage is ((1+10)/2=) 5.5+10= 15.5. If we multiply 15.5*.55 we get 8.525 damage for the full BAB attack.

I need a 15 to hit with my first iterative, so I have a 30% chance to hit, or a .3 multiplier. So .3*15.5= 4.65.

8.525+4.65= 13.175 damage per full-attack, 8.525 for a standard.

If it used this methodology, and had a function to take the statistical average (or better yet, the median) of each entry in the complete bestiary, you'd wind up making the ultimate tool to compare builds.

**Comment by Freymaurer** [comment]
Thank you for your first contribution! I will definitely look into this soon and add this feature to the toolbox!

**Comment by Taggerung559** [comment]
A copy/paste of a comment I added in to the reddit thread that spawned this issue:

"It winds up being a tiny bit more complicated than that due to crits. Lets say your weapon is a heavy flail (a 1d10, 19-20/x2 weapon).

For your first attack, you'd have a 45% chance of missing, a 45% chance of hitting, and a 10% chance of threatening a critical. In that 10% you'd have a 45% chance to fail the confirm, and a 55% chance to succeed. That puts you average multiplier to damage at (0.45+0.1x(.45+0.55x2))=0.605. Likewise, the average multiplier for the second attack would be 0.33, not 0.3.

That puts average damages at 9.3775 for standard action attack, and 14.4925 for a full attack."

There's a chance you were already aware this is how the math works out, I just felt like adding it in off-chance it would have otherwise slipped you mind if you ever go about implementing this functionality.

**Comment by Freymaurer** [comment]
So i started working on this but had to change some things to make the crit calculation more precise, as i previously had no possibility to add boni to only critical hit confirmation rolls (critical focus).
But this is now done and i will start with the rest.

**Comment by Freymaurer** [comment]
This feature is now implemented and added to the developer branch. It is also implemented in the QuickStart version.
